services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    pdir_content_migration_import.controller:
        class: Pdir\ContentMigrationBundle\Controller\ImportController
        public: true
        arguments:
            - "@contao.framework"
            - "@request_stack"
